sudo: false
language: cpp

# before_script:
#   - sudo apt-get update -qq
#   - sudo apt-get install 

compiler:
  - gcc
  - clang

branches:
  only:
    - devel

script:
  - mkdir build
  - cd build
  - cmake .. && make

